---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        #~ maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        when: midnight

    error_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        #~ maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        when: midnight

loggers:
    log_test:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
